#!/bin/bash

# Function to display script usage
function show_help() {
  echo "Usage: ./run_fahm.sh [OPTIONS]"
  echo "Run the 'fahm' binary on the 'highcompute' server via SSH"
  echo
  echo "Options:"
  echo "  -h, --help     Show help"
  echo "  -b             Run 'fahm -b'"
  exit 0
}

# Parse command-line arguments
run_b_flag=false

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      show_help
      ;;
    -b)
      run_b_flag=true
      shift
      ;;
    *)
      echo "Invalid option: $1"
      echo "Use -h or --help for more information."
      exit 1
      ;;
  esac
done

# Detect the CPU architecture
CPU_ARCH=$(uname -m)

# Set the Docker image based on the CPU architecture
if [[ $CPU_ARCH == "arm"* ]]; then
  DOCKER_IMAGE=jlenartjwp/jwt-nginx
else
  DOCKER_IMAGE=ghcr.io/max-lt/nginx-jwt-module:latest
fi

# Export the Docker image variable
export DOCKER_IMAGE

# SSH into the 'highcompute' server and run the appropriate command
if [[ $run_b_flag == true ]]; then
  echo "Running 'fahm -b' on 'highcompute' via SSH..."
  ssh highcompute "DOCKER_IMAGE=$DOCKER_IMAGE fahm -b"
else
  echo "Running 'fahm' on 'highcompute' via SSH..."
  ssh highcompute "DOCKER_IMAGE=$DOCKER_IMAGE fahm"
fi