version: '3'
services:
  fahm_backend:
    container_name: fahm_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always
    
  nextjs_app:
    container_name: nextjs_app
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ../frontend/.env
    restart: always
    
  nginx:
    image: jlenartjwp/jwt-nginx # ghcr.io/max-lt/nginx-jwt-module:latest for linux
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    restart: always
