version: '3'

services:
  fahm_backend:
    # container_name: fahm_backend
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 8080:8080
    env_file:
      - .env
    restart: always
    deploy:
      replicas: 3
    networks:
      - mynetwork

  nextjs_app:
    # container_name: nextjs_app
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - ../frontend/.env
    restart: always
    deploy:
      replicas: 3
    networks:
      - mynetwork

  nginx:
    image: ${DOCKER_IMAGE} # ghcr.io/max-lt/nginx-jwt-module:latest for linux
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/fahm.applesauce.co.in/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/fahm.applesauce.co.in/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - mynetwork

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/conf:/etc/letsencrypt/conf # Optional: customize Certbot configuration
      - ./certbot/www:/var/www/certbot # Optional: store webroot files for challenges
    command: certonly --webroot --webroot-path=/var/www/certbot -d fahm.applesauce.co.in
    restart: unless-stopped
    depends_on:
      - nginx

networks:
  mynetwork:
