version: '3'

services:
  fahm_backend:
    # container_name: fahm_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    deploy:
      replicas: 3
    networks:
      - mynetwork

  nextjs_app:
    # container_name: nextjs_app
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - ../frontend/.env
    restart: always
    deploy:
      replicas: 3
    networks:
      - mynetwork

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/fahm.applesauce.co.in/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/fahm.applesauce.co.in/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - mynetwork

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/www/certbot:/var/www/certbot
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email shanur.cse.nitap@gmail.com --agree-tos --no-eff-email --force-renewal -d fahm.applesauce.co.in
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
