version: '3'
services:
  fahm_backend:
    container_name: fahm_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always
    
  nginx:
    image: jlenartjwp/jwt-nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    restart: always

